spring:
  profiles:
    active: dev
    group:
      dev: dev, common, secret
      jiny: jiny-server, common, secret

#      local: common, secret

---
spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: jiny-server

  domain:
    name:
      http: http://localhost:80
      https: http://localhost:443
app:
  cors:
    allowed-origins:
      - "https://aaaa.co.kr"

---

spring:
  config:
    activate:
      on-profile: common

file:
  path: ${user.dir}/upload/profile
  servlet:
    multipart:
      max-file-size: 10MB  #?? ??? ??
      max-request-size: 100MB  #?? ?? ??

server:
  tomcat:
    max-swallow-size: -1

springdoc:
  swagger-ui:
    path: /doc

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.korit.ssedampet_back.entity

