spring:
  config:
    activate:
      on-profile: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.82.33.85:3306/ssedampet_db
    username: root
    password: ssedampet2580@
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 92766161312-tkqrk9sd4icppe56ipultkca1t8a18qg.apps.googleusercontent.com
            client-secret: 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
            scope:
              #- openid
              - profile
              - email
            redirect-uri: "https://ssedampet.store/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: GOOGLE

          naver:
            client-id: a9GYn0GbhvMKKwoQkHlo
            client-secret: 8EkHLooBdH
            client-authentication-method: client_secret_post
            scope:
              - email
            redirect-uri: "https://ssedampet.store/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: NAVER

          kakao:
            client-id: e8c7ae5ba127b229163827d1c8d42d2a
            client-secret: eKwhyPJRGdfUFo2wbPFjv0JwwSMgXGoF
            client-authentication-method: client_secret_post
            redirect-uri: "https://ssedampet.store/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: KAKAO

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  system-user-id: 1

jwt:
  secret: ssedampet-jwt-secret-key-2026-dev-very-secure
