spring:
  profiles:
    active: dev
    group:
      dev: dev, common, secret-dev
      jiny: jiny-server, common, secret-prod
      yunyeol: yunyeol-server, common, secret-prod
      hyojeong: hyojeong-server, common, secret-prod
      hyunwoo: hyunwoo-server, common, secret-prod

#      local: common, secret

---
spring:
  config:
    activate:
      on-profile: dev
app:
  cors:
    allowed-origins:
      - "http://localhost:5173"

---

spring:
  config:
    activate:
      on-profile: jiny-server

domain:
  name:
    http: http://ssedampet.shop
    https: https://ssedampet.shop
app:
  cors:
    allowed-origins:
      - "https://ssedampet.shop"

---

spring:
  config:
    activate:
      on-profile: yunyeol-server

domain:
  name:
    http: http://ssedampet.store
    https: https://ssedampet.store
app:
  cors:
    allowed-origins:
      - "https://ssedampet.store"

---

spring:
  config:
    activate:
      on-profile: hyojeong-server

domain:
  name:
    http: http://ssedampet.
    https: https://ssedampet.
app:
  cors:
    allowed-origins:
      - "https://ssedampet."

---

spring:
  config:
    activate:
      on-profile: hyunwoo-server

domain:
  name:
    http: http://ssedampet.
    https: https://ssedampet.
app:
  cors:
    allowed-origins:
      - "https://ssedampet."

---

spring:
  config:
    activate:
      on-profile: common

file:
  #path: ${user.dir}/upload/profile
  path: C:\gov\project\SsedamPet\SsedamPet_back
  servlet:
    multipart:
      max-file-size: 10MB  #?? ??? ??
      max-request-size: 100MB  #?? ?? ??

server:
  tomcat:
    max-swallow-size: -1

springdoc:
  swagger-ui:
    path: /doc



mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.korit.ssedampet_back.entity